# Config version: Do not touch this.
version: 1.0

# Language file. Will look for a file called <ARG>.yml in the lang folder.
# If the file does not exist, it will be automatically created for you to edit.
# Example: 'en' will look for /lang/en.yml
language: en

# Enable debug messages.
debug: false